---
# OS Updater - Ansible playbook to update Ubuntu hosts (REMOTE execution)
# This playbook runs from one Pi to update another Pi via ansible-admin user

- name: Update Ubuntu OS (Remote)
  hosts: all
  become: true
  gather_facts: true

  vars:
    reboot_timeout: 600
    post_reboot_delay: 60

  tasks:
    - name: Verify running as correct user
      ansible.builtin.debug:
        msg: "Running as user: {{ ansible_user_id }} on {{ inventory_hostname }}"

    - name: Check if updates are available
      ansible.builtin.shell: apt-get -s upgrade | grep -c "^Inst" || echo "0"
      register: updates_check
      changed_when: false

    - name: Set fact - updates available
      ansible.builtin.set_fact:
        updates_available: "{{ updates_check.stdout | int > 0 }}"

    - name: Display update status
      ansible.builtin.debug:
        msg: "{{ updates_available | ternary('Updates available', 'No updates available') }}"

    - name: Exit if no updates available
      ansible.builtin.meta: end_host
      when: not updates_available

    # Get running containers BEFORE updates
    - name: Get list of running Docker containers (before updates)
      ansible.builtin.shell: docker ps --format "{{ '{{' }}.Names{{ '}}' }}" | sort
      register: containers_before
      changed_when: false
      failed_when: false

    - name: Display running containers before update
      ansible.builtin.debug:
        msg: "Running containers ({{ containers_before.stdout_lines | default([]) | length }}): {{ containers_before.stdout_lines | default([]) }}"

    - name: Save container list to persistent location
      ansible.builtin.copy:
        content: "{{ containers_before.stdout }}"
        dest: "/var/tmp/containers_before_update.txt"

    # Install updates
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true

    - name: Install available updates
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
      register: update_result

    - name: Display update result
      ansible.builtin.debug:
        msg: "Updates installed successfully"

    # Check if reboot is required
    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Set fact - reboot required
      ansible.builtin.set_fact:
        reboot_required: "{{ reboot_required_file.stat.exists }}"

    - name: Display completion message for non-reboot updates
      ansible.builtin.debug:
        msg: "Updates completed successfully. No reboot required."
      when: not reboot_required

    # Reboot if required (Ansible will reconnect automatically)
    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible OS Updater"
        connect_timeout: 5
        reboot_timeout: "{{ reboot_timeout }}"
        pre_reboot_delay: 10
        post_reboot_delay: "{{ post_reboot_delay }}"
        test_command: uptime
      when: reboot_required
      register: reboot_result

    - name: Display reboot completion
      ansible.builtin.debug:
        msg: "System rebooted successfully and is back online"
      when: reboot_required

    # Verify Docker service is running after reboot
    - name: Wait for Docker service to be active
      ansible.builtin.systemd:
        name: docker
        state: started
      register: docker_service
      retries: 10
      delay: 5
      until: docker_service.status.ActiveState == "active"
      when: reboot_required

    - name: Give containers time to start
      ansible.builtin.pause:
        seconds: 30
      when: reboot_required

    # Verify containers after reboot
    - name: Get list of running Docker containers (after reboot)
      ansible.builtin.shell: docker ps --format "{{ '{{' }}.Names{{ '}}' }}" | sort
      register: containers_after
      changed_when: false
      failed_when: false
      when: reboot_required

    - name: Read expected container list
      ansible.builtin.slurp:
        src: /var/tmp/containers_before_update.txt
      register: containers_before_file
      when: reboot_required

    - name: Set fact - containers before (from file)
      ansible.builtin.set_fact:
        expected_containers: "{{ (containers_before_file.content | b64decode).split('\n') | select() | sort | list }}"
      when: reboot_required

    - name: Set fact - containers after
      ansible.builtin.set_fact:
        actual_containers: "{{ containers_after.stdout_lines | sort | list }}"
      when: reboot_required

    - name: Compare container lists
      ansible.builtin.set_fact:
        containers_match: "{{ expected_containers == actual_containers }}"
        missing_containers: "{{ expected_containers | difference(actual_containers) }}"
        extra_containers: "{{ actual_containers | difference(expected_containers) }}"
      when: reboot_required

    - name: Display container status
      ansible.builtin.debug:
        msg: |
          Container Status:
          - Expected: {{ expected_containers | length }} containers
          - Running: {{ actual_containers | length }} containers
          - Match: {{ containers_match }}
          {% if missing_containers | length > 0 %}
          - Missing: {{ missing_containers | join(', ') }}
          {% endif %}
          {% if extra_containers | length > 0 %}
          - Extra: {{ extra_containers | join(', ') }}
          {% endif %}
      when: reboot_required

    - name: Warn if containers don't match
      ansible.builtin.debug:
        msg: "WARNING: Not all containers are running after reboot!"
      when: reboot_required and not containers_match

    - name: Cleanup temporary file
      ansible.builtin.file:
        path: /var/tmp/containers_before_update.txt
        state: absent
      when: reboot_required

    # Final summary
    - name: Display final summary
      ansible.builtin.debug:
        msg: |
          OS Update Summary for {{ inventory_hostname }}:
          - Updates Installed: {{ updates_available }}
          - Reboot Performed: {{ reboot_required }}
          - Containers Verified: {{ containers_match | default(true) }}
          {% if missing_containers | default([]) | length > 0 %}
          - Action Required: Restart missing containers: {{ missing_containers | join(', ') }}
          {% endif %}