---
# OS Updater - Ansible playbook to update Ubuntu hosts
# This playbook:
# 1) Checks for available updates
# 2) Installs updates if available
# 3) Checks if a reboot is required
# 4) Reboots if needed with a timer to allow the playbook to complete
# 5) Sets a fact that can be used to trigger follow-up actions

- name: Update Ubuntu OS
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Time to wait before rebooting (seconds)
    reboot_delay: 30
    # Fact name to set when reboot is required
    reboot_required_fact: "reboot_required"

  tasks:
    - name: Check if updates are available
      ansible.builtin.command: apt-get -s upgrade | grep -c "^Inst"
      register: updates_available
      changed_when: false
      ignore_errors: true

    - name: Set fact - updates available
      ansible.builtin.set_fact:
        updates_available: "{{ updates_available.stdout | int > 0 }}"

    - name: Exit if no updates available
      ansible.builtin.meta: end_host
      when: not updates_available

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true
      when: updates_available

    - name: Install available updates
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
      register: update_result
      when: updates_available

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Set fact - reboot required
      ansible.builtin.set_fact:
        reboot_required: "{{ reboot_required_file.stat.exists }}"

    - name: Set output for GitHub Actions
      ansible.builtin.set_fact:
        github_output: "{{ reboot_required | ternary('reboot_required=true', 'reboot_required=false') }}"
      when: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: "{{ reboot_delay }}"
        post_reboot_delay: 30
      when: reboot_required
      register: reboot_result

    - name: Display reboot status
      ansible.builtin.debug:
        msg: "Reboot {{ reboot_result.changed | ternary('initiated', 'not needed') }}"

    - name: Write GitHub output file
      ansible.builtin.copy:
        content: "{{ github_output }}"
        dest: /tmp/github_output.txt
      when: reboot_required
      delegate_to: localhost
      run_once: true