- name: Docker networkS
  hosts: all
  become: true
  tasks:
    - name: Create VLAN 22
      community.docker.docker_network:
        name: VLAN22
        driver: macvlan
        ipam_config:
          - subnet: 10.2.2.0/24
            gateway: 10.2.2.1
        state: present
