name: technitium-dns1
fqdn: dns1.tomunsworth.net
container_host: pi3

# High-level flags for GitHub Actions orchestration
certificate: false             # needs Let's Encrypt cert
external_access: false         # should be exposed via Cloudflare Tunnel
dedicated_ip: true            # should get an IP from IP allocation CSV
update: true