
version: '3'
networks: 
 influxdb_net: 
    driver: bridge
    driver_opts:
        com.docker.network.bridge.host_binding_ipv4: 10.2.3.16
        com.docker.network.bridge.name: "influxdb_net"
        com.docker.network.bridge.enable_ip_masquerade: "true"
 grafana_net: 
    driver: bridge
    driver_opts:
        com.docker.network.bridge.host_binding_ipv4: 10.2.3.17
        com.docker.network.bridge.name: "grafana_net"
        com.docker.network.bridge.enable_ip_masquerade: "true"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: always
    networks:
      - influxdb_net
    ports:
      - '8086:8086'
    volumes:
      - /home/ubuntu/dockervol/influxdb/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    container_name: chronograf
    restart: always
    image: chronograf:latest
    networks:
      - influxdb_net
    ports:
      - '8888:8888'
    volumes:
      - /home/ubuntu/dockervol/chronograf-storage:/var/lib/chronograf
    depends_on:
      - grafana
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:latest
    networks:
      - grafana_net
    ports:
      - '3000:3000'
    volumes:
      - /home/ubuntu/dockervol/grafana-storage:/var/lib/grafana
      - /home/ubuntu/dockervol/grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}