
version: '3'
networks: 
 DB_net:
  name: DB_net
  internal: true
 
 ext_vlan:
  name: ext_vlan
  driver: ipvlan
  driver_opts:
    parent: eth0
    ipvlan_mode: l2
  ipam:
    config: 
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1

volumes:
  pgadmin:
  influxdb:
  chronograf:
  grafana_storage:
  grafana_provisioning:
  postgres_data:
  postgres_data_pgdata:


services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: always
    networks:
       ext_vlan:
          ipv4_address: ${influxdb_ip}
       DB_net:
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
  chronograf:
    container_name: chronograf
    restart: always
    image: chronograf:latest
    networks:
       ext_vlan:
          ipv4_address: ${chronograf_ip}
       DB_net:
    ports:
      - '8888:80'
    volumes:
      - chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - PORT=80
  
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:latest
    networks:
       ext_vlan:
          ipv4_address: ${grafana_ip}
       DB_net:
    ports:
      - '80:80'
    volumes:
      - grafana_storage:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_HTTP_PORT=80
  
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    networks: 
      - DB_net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql
      - postgres_data_pgdata:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    networks:
       ext_vlan:
          ipv4_address: ${pgadmin_ip}
       DB_net:
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin