
version: '3'
networks: 
   RP_DB_net:
    name: RP_DB_net
    internal: true
   HA_DB_net:
    name: HA_DB_net
    internal: true
   vlan23:
    name: vlan23
    driver: ipvlan
    driver_opts:
      parent: vlan23
      ipvlan_mode: l2
    ipam:
      config: 
        - subnet: 10.2.3.0/24
          gateway: 10.2.3.1
volumes:
  pgadmin:
  influxdb:
  chronograf:
  grafana_storage:
  grafana_provisioning:
  postgres_data:
  postgres_data_pgdata:


services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: always
    networks:
       HA_DB_net:
       RP_DB_net:
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_MODE = upgrade
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_USERNAME = ${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD = ${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG = ${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET = ${DOCKER_INFLUXDB_INIT_BUCKET}
  
  chronograf:
    container_name: chronograf
    restart: always
    image: chronograf:latest
    networks:
       vlan23:
          ipv4_address: ${chronograf_ip}
       RP_DB_net:
    ports:
      - '8888:80'
    volumes:
      - chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_TOEKN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - PORT=80
  
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:latest
    networks:
       vlan23:
          ipv4_address: ${grafana_ip}
       RP_DB_net:
    ports:
      - '80:80'
    volumes:
      - grafana_storage:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_HTTP_PORT=80
  
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    networks: 
      - RP_DB_net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql
      - postgres_data_pgdata:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    networks:
       vlan23:
          ipv4_address: ${pgadmin_ip}
       RP_DB_net:
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin