---
# Create dedicated admin user for cross-Pi SSH administration
# This playbook runs LOCALLY on each Pi runner

- name: Create Ansible Admin User
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    admin_user: "ansible-admin"
    admin_shell: "/bin/bash"

  tasks:
    - name: Create ansible-admin user
      ansible.builtin.user:
        name: "{{ admin_user }}"
        shell: "{{ admin_shell }}"
        create_home: yes
        state: present
        comment: "Ansible Cross-Pi Administration Account"

    - name: Add ansible-admin to sudo group
      ansible.builtin.user:
        name: "{{ admin_user }}"
        groups: sudo
        append: yes

    - name: Configure passwordless sudo for ansible-admin
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible-admin
        line: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"

    - name: Display user creation status
      ansible.builtin.debug:
        msg: "User {{ admin_user }} created successfully on {{ ansible_hostname }}"
