---
# SSH Key Setup - Deploy shared SSH keys from GitHub secrets
# Runs LOCALLY on each Pi runner
# Uses shared key pair stored in GitHub secrets - no manual exchange needed!

- name: Setup SSH Keys for Cross-Pi Administration
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    ssh_user: "ansible-admin"
    ssh_key_path: "/home/{{ ssh_user }}/.ssh/id_ed25519"
    # Key files will be passed from workflow or can be specified manually
    ssh_private_key_file: "/tmp/ssh_private_key"
    ssh_public_key_file: "/tmp/ssh_public_key"
    
  tasks:
    - name: Read private key from file
      ansible.builtin.slurp:
        src: "{{ ssh_private_key_file }}"
      register: private_key_content
      failed_when: false

    - name: Read public key from file
      ansible.builtin.slurp:
        src: "{{ ssh_public_key_file }}"
      register: public_key_content
      failed_when: false

    - name: Fail if key files not found
      ansible.builtin.fail:
        msg: "SSH key files not found at {{ ssh_private_key_file }} or {{ ssh_public_key_file }}"
      when: private_key_content.failed or public_key_content.failed

    - name: Set fact for private key
      ansible.builtin.set_fact:
        ssh_private_key: "{{ private_key_content.content | b64decode }}"

    - name: Set fact for public key
      ansible.builtin.set_fact:
        ssh_public_key: "{{ public_key_content.content | b64decode }}"

    - name: Check if ansible-admin user exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ ssh_user }}"
      register: user_check
      failed_when: false

    - name: Fail if ansible-admin user doesn't exist
      ansible.builtin.fail:
        msg: "User {{ ssh_user }} does not exist. Run create_admin_user.yml first!"
      when: user_check.ansible_facts is not defined or ssh_user not in user_check.ansible_facts.getent_passwd

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ ssh_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Deploy private SSH key from GitHub secret
      ansible.builtin.copy:
        content: "{{ ssh_private_key }}"
        dest: "{{ ssh_key_path }}"
        mode: '0600'
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Deploy public SSH key from GitHub secret
      ansible.builtin.copy:
        content: "{{ ssh_public_key }}"
        dest: "{{ ssh_key_path }}.pub"
        mode: '0644'
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Add public key to authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ ssh_user }}"
        key: "{{ ssh_public_key }}"
        state: present

    - name: Create SSH config for cross-Pi access
      ansible.builtin.copy:
        dest: "/home/{{ ssh_user }}/.ssh/config"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0600'
        content: |
          Host pi3
            HostName 10.2.4.20
            User {{ ssh_user }}
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          
          Host pi4
            HostName 10.2.4.10
            User {{ ssh_user }}
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null

    - name: Test SSH connectivity to other Pi
      ansible.builtin.command:
        cmd: "ssh -o BatchMode=yes -o ConnectTimeout=5 {{ 'pi4' if ansible_hostname == 'pi3' else 'pi3' }} echo 'SSH test successful'"
      become_user: "{{ ssh_user }}"
      register: ssh_test
      failed_when: false
      changed_when: false

    - name: Display SSH test result
      ansible.builtin.debug:
        msg: "{{ 'SSH connectivity verified!' if ssh_test.rc == 0 else 'SSH test failed - this is normal if other Pi has not been configured yet' }}"

    - name: Display completion status
      ansible.builtin.debug:
        msg: |
          ========================================
          SSH Setup Complete on {{ ansible_hostname }}!
          ========================================
          - Private key deployed from GitHub secret
          - Public key deployed and added to authorized_keys
          - SSH config created for cross-Pi access
          - Ready for cross-Pi administration
          ========================================
