---
- name: Add container IP to Mikrotik NATAllowed address list
  hosts: localhost
  gather_facts: no
  
  vars:
    address_list_name: "NATAllowed"
    container_ip: "{{ allocated_ip }}"
    mikrotik_host: "{{ vars_mikrotik_ip }}"
    mikrotik_user: "{{ vars_mikrotik_user }}"
    mikrotik_password: "{{ ansible_password }}"
    mikrotik_port: "{{ vars_mikrotik_port | default(8728) | int }}"
  
  tasks:
    - name: Validate input variables
      fail:
        msg: "Required variables not set: container_name={{ container_name }}, allocated_ip={{ allocated_ip }}"
      when: container_name is not defined or allocated_ip is not defined

    - name: Check if address already exists in NATAllowed list
      community.routeros.api:
        hostname: "{{ mikrotik_host }}"
        username: "{{ mikrotik_user }}"
        password: "{{ mikrotik_password }}"
        port: "{{ mikrotik_port }}"
        path: "ip/firewall/address-list"
        query:
          list: "{{ address_list_name }}"
          address: "{{ container_ip }}"
      register: existing_address
      no_log: flase
      
    - name: Display existing addresses
      debug:
        msg: "Found {{ existing_address.msg | length }} existing entries for {{ container_ip }}"
        verbosity: 1

    - name: Add IP to NATAllowed address list
      community.routeros.api:
        hostname: "{{ mikrotik_host }}"
        username: "{{ mikrotik_user }}"
        password: "{{ mikrotik_password }}"
        port: "{{ mikrotik_port }}"
        path: "ip/firewall/address-list"
        data:
          list: "{{ address_list_name }}"
          address: "{{ container_ip }}"
          comment: "{{ container_name }}"
      register: add_result
      when: existing_address.msg | length == 0
      no_log: true
      
    - name: Display add result
      debug:
        msg: |
          IP {{ container_ip }} ({{ container_name }}) successfully added to {{ address_list_name }} address list.
      when: existing_address.msg | length == 0

    - name: Display skip message
      debug:
        msg: |
          IP {{ container_ip }} already exists in {{ address_list_name }} address list. Skipping add.
      when: existing_address.msg | length > 0
