---
- name: Validate VLAN configuration
  hosts: all
  become: true
  gather_facts: true

  vars:
    vlan_interfaces:
      - vlan22
      - vlan23
      - vlan24
      - vlan25
      - vlan26
    expected_vlan24_ip: "10.2.4.30"
    expected_gateway: "10.2.4.1"
    dns_test_host: "google.com"

  tasks:

    - name: Check that VLAN interfaces exist
      ansible.builtin.command: ip link show {{ item }}
      register: vlan_links
      changed_when: false
      failed_when: vlan_links.rc != 0
      loop: "{{ vlan_interfaces }}"

    - name: Get IP addresses for VLAN24
      ansible.builtin.command: ip -4 addr show dev vlan24
      register: vlan24_ip_output
      changed_when: false

    - name: Verify VLAN24 has the correct IP
      ansible.builtin.assert:
        that:
          - "'{{ expected_vlan24_ip }}' in vlan24_ip_output.stdout"
        fail_msg: "vlan24 does not have IP {{ expected_vlan24_ip }}"

    - name: Ping VLAN24 gateway to verify routing
      ansible.builtin.command: ping -c 2 {{ expected_gateway }}
      register: ping_gateway
      changed_when: false
      failed_when: ping_gateway.rc != 0

    - name: Test DNS resolution
      ansible.builtin.command: getent hosts {{ dns_test_host }}
      register: dns_test
      changed_when: false
      failed_when: dns_test.rc != 0

    - name: Display assigned IPs
      ansible.builtin.debug:
        var: ansible_all_ipv4_addresses
