---
- name: Create A record in Technitium DNS
  hosts: localhost
  gather_facts: false

  vars:
    # Expected inputs:
    # - dns_server
    # - fqdn
    # - allocated_ip
    # - technitium_api_token
    api_port: 8443
    record_name: "{{ fqdn.split('.')[0] }}"
    dns_zone: "{{ fqdn.split('.', 1)[1] }}"
    technitium_api_url: >-
      https://{{ dns_server }}:{{ api_port }}/api/zones/records/add?token={{ technitium_api_token }}&domain={{ fqdn }}&zone={{ dns_zone }}&type=A&ttl=3600&ipAddress={{ allocated_ip }}&ptr=true

  tasks:
    - name: Add A record via Technitium API
      ansible.builtin.uri:
        url: "{{ technitium_api_url | urlencode | urldecode }}"
        method: GET
        return_content: true
        status_code:
          - 200
          - 400  # sometimes returned if record exists
      register: add_record_response

    - name: Show response from Technitium
      ansible.builtin.debug:
        var: add_record_response.content