---
- name: Create A record in Technitium DNS
  hosts: localhost
  gather_facts: false

  vars:
    # Expected inputs:
    # - dns_server
    # - fqdn
    # - allocated_ip
    technitium_api_token: "{{technitium_api_token}}"
    api_port: 53443
    record_name: "{{ fqdn.split('.')[0] }}"
    dns_zone: "{{ fqdn.split('.', 1)[1] }}"
    technitium_api_url: >-
      https://{{ dns_server }}:{{ api_port }}/api/zones/records/add?token={{ technitium_api_token }}&domain={{ fqdn }}&zone={{ dns_zone }}&type=A&ttl=3600&ipAddress={{ allocated_ip }}&ptr=true

  tasks:
    - name: Add A record via Technitium API
      ansible.builtin.uri:
        url: "{{ technitium_api_url | urlencode | urldecode }}"
        method: GET
        return_content: true
        status_code:
          - 200
          - 400  # sometimes returned if record exists
      register: add_record_response

    - name: Parse JSON response
      ansible.builtin.set_fact:
        response_json: "{{ add_record_response.json }}"
    - name: Fail if API returned error
      ansible.builtin.debug:
        msg: "Technitium API response status: {{ response_json.status }}"

    - name: If API did not return ok, check existing DNS record
      block:
        - name: Lookup existing A record via DNS
          ansible.builtin.command:
            cmd: "dig +short @{{ dns_server }} {{ fqdn }} A"
          register: dns_lookup
          failed_when: false
          changed_when: false

        - name: Set existing_ip fact
          ansible.builtin.set_fact:
            existing_ip: "{{ dns_lookup.stdout_lines[0] | default('') }}"

        - name: Debug existing IP
          ansible.builtin.debug:
            msg: "Existing A record for {{ fqdn }} -> '{{ existing_ip }}'"

        - name: Succeed when existing record matches requested IP
          ansible.builtin.debug:
            msg: "A record for {{ fqdn }} already exists and points to {{ allocated_ip }}; skipping creation."
          when: existing_ip == allocated_ip

        - name: Fail when existing record points to a different IP
          ansible.builtin.fail:
            msg: "A record for {{ fqdn }} exists and points to {{ existing_ip }} (expected {{ allocated_ip }}). Please remove or update it first."
          when: existing_ip != '' and existing_ip != allocated_ip

        - name: Fail when API returned error and no existing record found
          ansible.builtin.fail:
            msg: "Technitium API returned an error and no existing A record was found for {{ fqdn }}. API message: {{ response_json.message | default(response_json.status) }}"
          when: existing_ip == ''
      when: response_json.status != 'ok'

    - name: Show response from Technitium
      ansible.builtin.debug:
        var: add_record_response.content