version: '3'
networks: 
 DB_net:
  name: DB_net
  internal: true
 
 mqtt_net:
  name: mqtt_net
  internal: true

 ext_vlan:
  name: ext_vlan
  driver: ipvlan
  driver_opts:
    parent: eth0
    ipvlan_mode: l2
  ipam:
    config: 
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1

volumes:
  nodered_data:
  mosquitto:
  homeassistant_config:

services: 
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Australia/Sydney
    ports:
      - "1880:1880"
    networks:
       ext_vlan:
          ipv4_address: ${nodered_ip}
       DB_net:
       mqtt_net:
    volumes:
      - nodered_data:/data
    restart: always
  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    networks:
       ext_vlan:
          ipv4_address: ${mosquitto_ip}
       mqtt_net:
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto:/mosquitto/
    restart: always    
  
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Australia/Sydney
    ports:
      - "8123:8123"
    networks:
       ext_vlan:
          ipv4_address: ${homeassistant_ip}
       DB_net:
       mqtt_net:
    volumes:
      - homeassistant_config:/config
    restart: always