version: '3'
networks: 
 HA_DB_net:
  name: HA_DB_net
  internal: true
 
 HA_mqtt_net:
  name: HA_mqtt_net
  internal: true

 vlan23:
  name: vlan23
  driver: ipvlan
  driver_opts:
    parent: vlan23
    ipvlan_mode: l2
  ipam:
    config: 
      - subnet: 10.2.3.0/24
        gateway: 10.2.3.1

volumes:
  nodered_data:
  mosquitto:
  homeassistant_config:

services: 
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Australia/Sydney
    ports:
      - "1880:1880"
    networks:
       vlan23:
          ipv4_address: ${nodered_ip}
       HA_DB_net:
       HA_mqtt_net:
    volumes:
      - nodered_data:/data
    restart: always
  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    networks:
       vlan23:
          ipv4_address: ${mosquitto_ip}
       HA_mqtt_net:
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto:/mosquitto/
    restart: always    
  
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Australia/Sydney
    ports:
      - "8123:8123"
    networks:
       vlan23:
          ipv4_address: ${homeassistant_ip}
       HA_mqtt_net:
       cloudflare_ext:
    volumes:
      - homeassistant_config:/config
    restart: always