# infrastructure/software/docker-install/docker_setup.yml
- name: Install Docker
  hosts: all
  become: true
  roles:
    - geerlingguy.docker

  tasks:
    - name: Add runner user to docker group
      user:
        name: runner
        groups: docker
        append: yes