version: '3.3'
networks: 
 firefly_net: 
    driver: bridge
    driver_opts:
        com.docker.network.bridge.host_binding_ipv4: 10.2.3.19
        com.docker.network.bridge.name: "portainer"
        com.docker.network.bridge.enable_ip_masquerade: "true"
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - /home/ubuntu/dockervol/firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks: 
      - firefly_net
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: "postgres:latest"
    restart: unless-stopped
    environment:
       - POSTGRES_PASSWORD=limping-landowner-yam
       - POSTGRES_USER=firefly
    volumes:
      - /home/ubuntu/dockervol/firefly_iii_db/postgress:/var/lib/postgresql
      - /home/ubuntu/dockervol/firefly_iii_db/data:/var/lib/postgresql/data
    networks: 
      - firefly_net
  import:
    image: "fireflyiii/data-importer:latest"
    restart: unless-stopped
    environment: 
      - FIREFLY_III_ACCESS_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0MCIsImp0aSI6IjQ0OTYzZGIwZDE5MjU4MWM0MDRjZTc4MTMxZTJhM2ZhMWQ0ZWM3ODQwZmYyOTIwM2E5ODY0MjlkMzZlMTBhYWUzYjZhODc5MGQzMWE1YzFiIiwiaWF0IjoxNjY1MTk3NDQ2LjQ2NDE5LCJuYmYiOjE2NjUxOTc0NDYuNDY0MjA4LCJleHAiOjE2OTY3MzM0NDYuMjQ4NzA0LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.EQBI0ZxXBjdOZ2ItpQuO7lH3uNa3-DhTpYoaT9m69-rfHZxzGaXtZdH49DWTIlTkn3FsOCXb9ds5jwG0uT5f-HwljWqk-IczUeiAp-HSw3ut1Go5vTxNXMvbMQbohi82sfYBAqqjdNjwR3suULf2v__-dhOI3X1FvhfSygL88pfjfo9d8xRZ5LPYSki5qpTeEoFKdA8rMu7xsPNS00nW8eKlFPPhXMeb32qu6EicJujW815pDU8vnl5luVvMxnMTm5G6wJqoHTNYMCs5NNGpz2c-HawQ9UZNE-E63azml1WCCnIB7Eds8z8d-skSSTKz6OGpHM5ldft_INx2EHXnyogQGAnoWK8or0KHlvUra0wCHPGYXOwVCXWOTdiAuBtoyY6y_bprHiv8mSVOPRXgJfb4OYPRteQrK_mF3zjkiio4O1cZpuQUyJ2OY82ZltfrP5hrDylFWqlJ1O21HwyweBjzGDOV4IT4aeAVpsPX00ZjV1kjZOQTEuKSvHGwljSLovnkz1WX4T6BFMUljjcR6O4djSeN19vPWIxqytA7wRVYoa_vx_Mw7ZnfMXXurPTUTkLTOqerThsVhIkZ2jGsv7eSTmMS74pL7xBUG6pDKbci-Hoz1O1JQotDKbcc1rRDaa3ASUplDesJ3caXcNY70M3GZtOPNPMirpHTmA8Rd2s"
      - FIREFLY_III_URL="http://app:8080"
    networks: 
      - firefly_net
    ports:
      - 81:8080
volumes:
   firefly_iii_upload:
   firefly_iii_db: