version: '3.3'
networks: 
 firefly_net: 
    driver: bridge
    driver_opts:
        com.docker.network.bridge.host_binding_ipv4: 10.2.3.19
        com.docker.network.bridge.name: "portainer"
        com.docker.network.bridge.enable_ip_masquerade: "true"
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks: 
      - firefly_net
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=limping-landowner-yam
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db: