version: '3.3'
networks: 
 firefly_net: 
    driver: bridge
    driver_opts:
        com.docker.network.bridge.host_binding_ipv4: 10.2.3.19
        com.docker.network.bridge.name: "portainer"
        com.docker.network.bridge.enable_ip_masquerade: "true"
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - /home/ubuntu/dockervol/firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks: 
      - firefly_net
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: "postgres:latest"
    restart: unless-stopped
    environment:
       - POSTGRES_PASSWORD=limping-landowner-yam
       - POSTGRES_USER=firefly
    volumes:
      - /home/ubuntu/dockervol/firefly_iii_db/postgress:/var/lib/postgresql
      - /home/ubuntu/dockervol/firefly_iii_db/data:/var/lib/postgresql/data
    networks: 
      - firefly_net
  import:
    image: "fireflyiii/data-importer:latest"
    restart: unless-stopped
    environment: 
      - FIREFLY_III_ACCESS_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI2ZTA4MTgyMWNmM2YwNjJmZjBkNGRjMzg5NDFjYzA3ODg2NDQ0ODNiYzIzMDNjNTMyMzU1ZjhjMzBiNzBjMzI5ZTQxOGEyMTBhYzdkZjAiLCJpYXQiOjE2NDE4OTU2MzAuNzYyOTksIm5iZiI6MTY0MTg5NTYzMC43NjMwMTUsImV4cCI6MTY3MzQzMTYzMC42NzAwMzgsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.cMqGpaYS5sBHk6qyPQ4j7vMuR2mOPRUE0VrA9fy4CeR-pG2zD-RbWlgB2Cz2RnEUiW0JOK2Pr-_KrS5GQHTKidYRiJCJHnOWRH9rmPkPkIl8kyc5IZCMuqBUOcLFtiWs1bdzxPT0LweLsEUDdIe3HMgC6jtU08JSHyrq9uvuEKfjh20nWp0romGfDjnPsaYguvjnRSYepkAilpWkiIl21IISGvl14UKmUS9J7PdPcoKx1ct1mt9H97oFPYbALZafJ7VqRnacK0unb7qaWu1KDNhm7GfV496Sru5e-Ya4gCkTkur655c39OoQiYy6bAI3nEutMt3mo1RI3TUyYlOyi5r7PW5tUXB4c-V8A9-hUvlgLG3BLO1xcJ1TTK8eeJbeklfbsTNT1h74eYoazuaZqrjqHrYA2yns2jf0jRpy6ro9RDY7kp7W2oiwJSuhvg-JTrmo1Si_ss8qKyzxBEjgSFgvP6OrDZZ0efuuzI5JcnD3_ijnSm14ivPkdZgDTvNHkO9-fUk7cB0FUkm9fH3aO05E4usNR9aPIOjkrjZutJUJNAQtYMoILI5MLTNwwRK43R72PqEmf_1HHEvOCGtNLi-JjSGf3UirqM51FO_XFZeVyMjpIlkojtyD7QXwlVWEk4wcXqs47T1Jr1iB3Mt13HGNago8NrMoTd20xq3RG8U"
      - FIREFLY_III_URL="http://app:8080"
    networks: 
      - firefly_net
    ports:
      - 81:8080
volumes:
   firefly_iii_upload:
   firefly_iii_db: