
version: '3'
networks: 
 influxdb_net: 
    driver: bridge
    driver_opts:
        com.docker.network.bridge.host_binding_ipv4: 10.2.3.16
        com.docker.network.bridge.name: "influxdb_net"
        com.docker.network.bridge.enable_ip_masquerade: "true"

services:
  influxdb:
    image: influxdb:1.8
    volumes:
      # Mount for influxdb data directory and configuration
      - /home/ubuntu/dockervol/influxdb/:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - influxdb_net
  # Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:1.8
    volumes:
      # Mount for influxdb data directory and configuration
      - /home/ubuntu/dockervol/influxcli/:/var/lib/influxdb2:rw
      - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=Dn20xwl2fl2Rwkspq!#
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=KFC
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=AReallyLongAdminToken
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - /home/ubuntu/dockervol/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=KFC
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=AReallyLongAdminToken
    depends_on:
      - influxdb_cli
volumes:
  influxdb2: