name: Check & Renew Let's Encrypt Certificates

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  check-renew:
    environment: Production
    runs-on: [self-hosted,Production]

    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Create Cloudflare credentials file
      run: |
        cd ~/pi-dockercompose/inf-services/certbot/conf
        [ -f cloudflare.ini ] && rm cloudflare.ini
        echo "dns_cloudflare_api_token = $CF_API_TOKEN" >> cloudflare.ini
        chmod 600 cloudflare.ini

    - name: Install OpenSSL (for cert date checking)
      run: sudo apt-get install -y openssl

    - name: Check and Renew Certificates
      run: |
        cd ~/pi-dockercompose/inf-services/
        DAYS_THRESHOLD=30
        LIVE_DIR="$PWD/certbot/conf/live"

        if [ ! -d "$LIVE_DIR" ]; then
          echo "No existing certs found in $LIVE_DIR"
          exit 0
        fi

        for DOMAIN in $(ls -1 "$LIVE_DIR"); do
          CERT_PATH="$LIVE_DIR/$DOMAIN/fullchain.pem"

          echo "Processing domain: $DOMAIN"

          if [ ! -f "$CERT_PATH" ]; then
            echo "No certificate found for $DOMAIN. Skipping..."
            continue
          fi

          EXPIRY_DATE=$(openssl x509 -enddate -noout -in "$CERT_PATH" | cut -d= -f2)
          EXPIRY_EPOCH=$(date -d "$EXPIRY_DATE" +%s)
          NOW_EPOCH=$(date +%s)
          DAYS_LEFT=$(( (EXPIRY_EPOCH - NOW_EPOCH) / 86400 ))

          echo "Certificate for $DOMAIN expires in $DAYS_LEFT days."

          if [ "$DAYS_LEFT" -le "$DAYS_THRESHOLD" ]; then
            echo "Renewing $DOMAIN (expires in $DAYS_LEFT days)"
            docker run --rm \
              -v "$PWD/certbot/conf:/etc/letsencrypt" \
              -v "$PWD/certbot/www:/var/www/certbot" \
              certbot/dns-cloudflare \
              certonly \
              --dns-cloudflare \
              --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini \
              -d "$DOMAIN" \
              --non-interactive --agree-tos --email mail@tomunsworth.net \
              --preferred-challenges dns-01
          else
            echo "No renewal needed for $DOMAIN"
          fi
        done

    - name: Restart NGINX
      run: |
        cd ~/pi-dockercompose/inf-services/
        docker-compose restart nginx
