name: DNS Internal New A Record

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      allocated_ip:
        required: false
        type: string
      docker_host:
        required: false
        type: string
      fqdn:
        required: false
        type: string

jobs:
  create-a-record:
    runs-on: ${{ inputs.docker_host }}
    environment: ${{ inputs.environment }}
    env:
      BASE_DIR: 'infrastructure/dns/internal/'
      DNS_API: ${{ secrets.TECHITIUM_DNS_API_KEY}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Ansible inventory
        run: |
          cd $BASE_DIR
          echo "localhost ansible_connection=local" > inventory.ini
      - name: Run Ansible playbook
        run: |
          cd $BASE_DIR
          echo "${{ secrets.SUDO }}" | sudo -S ansible-playbook create_A_record.yml \
            -i inventory.ini -e "technitium_api_token=$DNS_API allocated_ip=${{ inputs.allocated_ip }} fqdn=${{ inputs.fqdn }} dns_server=${{vars.dns_server}}"