name: Docker Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'Test'
jobs:
  setup:
    runs-on: ${{ 
      (inputs.environment == 'Dev') && fromJSON('["self-hosted", "dev"]') ||
      (inputs.environment == 'Test') && fromJSON('["self-hosted", "test"]') ||
      fromJSON('["self-hosted", "prod"]') }}
    env:
      BASE_DIR: 'infrastructure/host/software'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Ensure Ansible is Installed
        run: |
          if ! command -v ansible >/dev/null 2>&1; then
            echo "Ansible not found. Installing..."
            echo "${{ secrets.SUDO }}" | sudo -S apt update
            echo "${{ secrets.SUDO }}" | sudo -S apt install -y ansible
          else
            echo "Ansible already installed."
          fi

      - name: Install Required role
        run: |
          cd $BASE_DIR
          ansible-galaxy install geerlingguy.docker -p roles 
      - name: Create Ansible inventory
        run: |
          cd $BASE_DIR
          echo "localhost ansible_connection=local" > inventory.ini
     
      - name: Run Ansible playbook
        run: |
          cd $BASE_DIR
          echo "${{ secrets.SUDO }}" | sudo -S ansible-playbook docker_setup.yml \
            -i inventory.ini
