name: VLAN Setup
on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      environment:
        required: true
        type: string
      runs_on:
        required: true
        type: string
jobs:
  setup-vlans:
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.environment }}

    env:
      BASE_DIR: 'infrastructure/host/network'

    steps:
      - name: Run network configuration
        run: |
          echo "Running Network setup for host: ${{ inputs.host }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Ensure Ansible is Installed
        run: |
          if ! command -v ansible >/dev/null 2>&1; then
            echo "Ansible not found. Installing..."
            echo "${{ secrets.SUDO }}" | sudo -S apt update
            echo "${{ secrets.SUDO }}" | sudo -S apt install -y ansible
          else
            echo "Ansible already installed."
          fi

      - name: Create Ansible inventory
        run: |
          cd $BASE_DIR
          echo "localhost ansible_connection=local" > inventory.ini

      - name: Run Ansible playbook
        run: |
          cd $BASE_DIR
          echo "${{ secrets.SUDO }}" | sudo -S ansible-playbook vlan_setup.yml \
            -i inventory.ini -e "runner=${{inputs.host}}"
      - name: Run VLAN validation playbook
        run: |
          cd $BASE_DIR
          echo "${{ secrets.SUDO }}" | sudo -S ansible-playbook validate_vlan.yml \
          -i inventory.ini -e "runner=${{inputs.host}}"