name: VLAN Setup

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/pi3/network/**'

jobs:
  setup-vlans:
    environment: Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Ensure Ansible is Installed
        run: |
          if ! command -v ansible >/dev/null 2>&1; then
            echo "Ansible not found. Installing..."
            sudo apt update
            sudo apt install -y ansible
          else
            echo "Ansible already installed."
          fi

      - name: Create Ansible inventory
        run: |
          cd infrastructure/pi3/network
          echo "localhost ansible_connection=local" > inventory.ini

      - name: Run Ansible playbook
        run: |
          cd infrastructure/pi3/network
          ansible-playbook vlan_setup.yml \
            -i inventory.ini
