name: Test Server - Docker Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'Test'
jobs:
  setup:
    runs-on: [self-hosted, test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Ensure Ansible is Installed
        run: |
          if ! command -v ansible >/dev/null 2>&1; then
            echo "Ansible not found. Installing..."
            echo "${{ secrets.SUDO }}" | sudo -S apt update
            echo "${{ secrets.SUDO }}" | sudo -S apt install -y ansible
          else
            echo "Ansible already installed."
          fi

      - name: Create Ansible inventory
        run: |
          cd infrastructure/software/docker-install
          echo "localhost ansible_connection=local" > inventory.ini

      - name: Run Ansible playbook
        run: |
          cd infrastructure/software/docker-install
          echo "${{ secrets.SUDO }}" | sudo -S ansible-playbook docker_setup.yml \
            -i inventory.ini